const Articles = [
    'shewinggum',
    'fromages blanc',
    'riz',
    'pattes completes',
    'blanc de poulet',
    'huile olive',
    'thon',
    'baguettes',
    'lait eloise',
    'lait chen',
    'gel douche',
    'dentifrice',
    'fromage rape',
    'pq',
    'viande boeuf hachee',
    'poisson',
    'savon main',
    'liquide vaiselle',
    'cafe thomas',
    'cafe chen',
    'filtre cafe',
    'lingette',
]

export default Articles;